### ISSUE TITLE
How to set redirectLoginUri?

### ISSUE THREAD

**Issue by madhuteja** [hadiidbouk/AppAuthWebView-Android#1]
I'm using IdentityServer4 as my STS and I'm having issues with setting the `redirectLoginUri` in AppAuthWebView-Android. I'm always getting the error "Web page not available" after success full authorization.
Here is my AppAuthWebViewData
`val data = AppAuthWebViewData()

        data.clientId = "mobileClient"
        data.authorizationEndpointUri = "http://10.0.2.2:5000/connect/authorize"
        data.clientSecret = ""
        data.discoveryUri = "n"
        data.redirectLoginUri = "mymobileclient://oidclogincallback"
        data.redirectLogoutUri = "mymobileclient://oidclogoutcallback"
        data.scope = "openid profile offline_access api1"
        data.tokenEndpointUri = "http://10.0.2.2:5000/connect/token"
        data.registrationEndpointUri = "n"
        data.responseType = ResponseTypeValues.CODE
        data.isGenerateCodeVerifier = true`

And also the same parameters set to the IdentityServer4.

Could you please give any example

**Comment by hadiidbouk** [comment]
Hello @madhuteja ,

The redirect login uri is used by the library you don't need to worry about it, if the onUserAuthorize method  has been called then everything is fine.

You can see below that i am receiving the AuthState Instance in onUserAuthorize, in this method you can do whatever you want since you are authorized now.

Just start your MainActivity and close the AuthActivity like so : 


```
 public class AuthActivity extends Activity implements IAppAuthWebViewListener {
            	.....
        
        @Override public void onUserAuthorize(AuthState authState) {
        		Intent mainIntent= new Intent(AuthActivity.this, MainActivity.class);
                        AuthActivity.this.startActivity(mainIntent);
        		finish();		
        	}
```

Also you should add all these methods to prevent any errors from the webview : 

```
                @Override public void showConnectionErrorLayout() {
            		mErrorLayout.setVisibility(View.VISIBLE);
            	}
            
            	@Override public void hideConnectionErrorLayout() {
            		mErrorLayout.setVisibility(View.INVISIBLE);
            	}
            
            	@Override public void showLoadingLayout() {
            		mLoadingLayout.setVisibility(View.VISIBLE);
            	}
            
            	@Override public void hideLoadingLayout() {
            		mLoadingLayout.setVisibility(View.INVISIBLE);
            	}
```

**Comment by madhuteja** [comment]
OK, I'm getting the `AuthState` in `onUserAuthorize` callback method. Before closing the AuthActivity, i'm seeing the Web page not available error for a second. So I thought I missed something.
Anyways thanks for your help.
