### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by blennerSilva** [hadiidbouk/AppAuthWebView-Android#5]
WebView webView = findViewById(R.id.WebView);

        AppAuthWebViewData data = new AppAuthWebViewData();
        data.setClientId("10399857-98ddd6c572a9");
        data.setAuthorizationEndpointUri("https://ids-dev.global.net/nidp/oauth/nam/authz");
        data.setClientSecret("m7C0PUZh2micvwe35wTnhaiauiqb7hbIstgIGhm6m3KNklmavo3g");
        data.setDiscoveryUri("n");
        data.setScope("");
        data.setTokenEndpointUri("https://ids-dev.lobal.net/nidp/oauth/nam/token");
        data.setRegistrationEndpointUri("https://ids-dev.obal.net/nidp/oauth/nam/clients");
        data.setResponseType("JSON");
        data.setGenerateCodeVerifier(false);

        AppAuthWebView appAuthWebView = new AppAuthWebView
                .Builder()
                .webView(webView)
                .authData(data)
                .listener(this)
                .build();

        appAuthWebView.performLoginRequest();

hello this is my code above key and urls were editted and on perform login im getting uristring null pointer would you guys help me implenment please?

**Comment by hadiidbouk** [comment]
Hello, 

Can you show me some logs, please ? 
Did the login view appear?

You should add atleast "`openid`" in scope.

I recommend you to read more about `openid`, and try to make it work with the [AppAuth-Android](https://github.com/openid/AppAuth-Android) first then copy the configuration to this library.

Also, remove your sensitive information.

**Comment by Martin-Indico** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.indico.openidtest, PID: 2257
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at java.lang.String.contains(String.java:2126)
        at com.hadiidbouk.appauthwebview.AppAuthWebView$AppAuthWebViewClient.shouldOverrideUrlLoading(AppAuthWebView.java:250)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at apM.a(SourceFile:1)
        at xq.b(SourceFile:81)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(SourceFile:172)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
````
Getting this error with this settup:
```
val authRequest = AppAuthWebViewData().apply {
                clientId = "*************"
                clientSecret = ""*************""
                authorizationEndpointUri = serviceConfiguration.authorizationEndpoint.toString()
                redirectLoginUri = "*************"
                redirectLogoutUri = "*************"
                discoveryUri = "n"
                scope = "openid profile"
                tokenEndpointUri = serviceConfiguration.tokenEndpoint.toString()
                registrationEndpointUri = serviceConfiguration.registrationEndpoint.toString()
                responseType = "code"
                isGenerateCodeVerifier = false
            }
val appAuthWebView = AppAuthWebView.Builder()
                .webView(webView)
                .authData(authRequest)
                .listener(this)
                .build()
appAuthWebView.performLoginRequest()
```

Im utilizing the result of a service configuration request to set some of the properties, these are tested and not null. Code works with the regular AppAuth-Android

**Comment by hadiidbouk** [comment]
I will check it and get back to you soon

**Comment by Martin-Indico** [comment]
I found out that registration url were not set, changing this fixed the problem.

Get Outlook for Android<https://aka.ms/ghei36>




On Sat, Nov 24, 2018 at 1:50 PM +0100, "Hadi Dbouk" <notifications@github.com<mailto:notifications@github.com>> wrote:


I will check it and get back to you soon

**Comment by hadiidbouk** [comment]
Great then !
If you want any help don't hesitate to add a new issue

**Comment by Martin-Indico** [comment]
I will, thanks

Get Outlook for Android<https://aka.ms/ghei36>




On Sat, Nov 24, 2018 at 1:56 PM +0100, "Hadi Dbouk" <notifications@github.com<mailto:notifications@github.com>> wrote:


Great then !
If you want any help don't hesitate to add a new issue

**Comment by shishirshettygit** [comment]
Please 'Close' this bug, if the issue has been resolved.
