### ISSUE TITLE
Provide one sample example

### ISSUE THREAD

**Issue by sagarsrao** [hadiidbouk/AppAuthWebView-Android#6]
Hello Developer,

Please provide one sample example your library. And your sample app is just empty.

Thanks,
Sagar

**Comment by hadiidbouk** [comment]
Hello,

I will do it later for sure, I am little busy these days

Best

**Comment by stepenik** [comment]
When will be available example ? @hadiidbouk

**Comment by Roman174** [comment]
When will be available example ? @hadiidbouk

**Comment by hadiidbouk** [comment]
I will try to add an example in the next two weeks.

**Comment by hadiidbouk** [comment]
A Sample is added now #8 however, the whole library's code will change.
